### ISSUE TITLE
about FastOpts

### ISSUE THREAD

**Issue by joecabezas** [kefik/MarioAI#1]
hello!, there is any other way to set receptive field width and height than this?

`String options =
                FastOpts.VIS_ON_2X +
                FastOpts.LEVEL_06_GOOMBA +
                " -rfw 8 -rfh 8";`

**Comment by kefik** [comment]
Hi! Not everything is included in FastOpts, see MarioOptions for more enums.

However, I've pushed change to the FastOpts adding 

`static String AI_RECEPTIVE_FIELD(int widht, int height)`

method as a shortcut.

Cheers!

**Comment by joecabezas** [comment]
thank you so much for your assistance, I love your project, thanks!
